version: '3.8'

services:
  twitter-automation:
    build: .
    container_name: twitter-automation-ai
    volumes:
      - ./config:/app/config
      - ./media_files:/app/media_files
      - ./.wdm_cache:/app/.wdm_cache
      - global_twitter_queue:/app/twitter_queue
    restart: unless-stopped

volumes:
 global_twitter_queue:
   external: true