name: Deploy to VPS

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    # Define the environment for secrets and variables.
    # This should be configured in your repository settings under Settings > Environments.
    environment: "PROD"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "~/projects/${{ vars.APP_NAME }}/"
          overwrite: true