name: Deploy to VPS

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    environment: "PROD"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "~/projects/${{ vars.APP_NAME }}/"
          overwrite: true

      - name: Run remote commands on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            export TRACKER_001_COOKIE=${{ secrets.TRACKER_001_COOKIE }}

            cd ~/projects/${{ vars.APP_NAME }}/

            # If the app is running, stop it
            docker compose -f docker-compose.yml down || true
            
            # Build and start the app using Docker Compose
            docker compose -f docker-compose.yml up -d --build